apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqliteinstances.kubelitedb.fortytwoapps.tech
spec:
  group: kubelitedb.yourdomain.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbName:
                  type: string
                  description: "The name of the SQLite database."
                storage:
                  type: string
                  description: "The amount of storage allocated for the SQLite database."
                replicas:
                  type: integer
                  description: "The number of replicas for the SQLite database."
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "The current phase of the SQLite instance."
  scope: Namespaced
  names:
    plural: sqliteinstances
    singular: sqliteinstance
    kind: SQLiteInstance
    shortNames:
      - sql
  additionalPrinterColumns:
    - name: DB Name
      type: string
      description: "The name of the SQLite database"
      jsonPath: ".spec.dbName"
    - name: Storage
      type: string
      description: "The amount of storage allocated for the SQLite database"
      jsonPath: ".spec.storage"
    - name: Replicas
      type: integer
      description: "The number of replicas for the SQLite database"
      jsonPath: ".spec.replicas"
    - name: Phase
      type: string
      description: "The current phase of the SQLite instance"
      jsonPath: ".status.phase"
